[versions]
agp = "8.12.3"
kotlin = "2.2.21"
android-minSdk = "24"
android-compileSdk = "36"
androidx-lifecycle = "2.9.6"
androidx-browser = "1.9.0"
androidx-core = "1.17.0"
androidx-navigation = "2.9.1"
androidx-startup = "1.2.0"
arrow = "2.2.0"
compose = "1.9.3"
androidx-compose = "1.9.4"
maven-publish = "0.34.0"
multiplatform-locale = "0.9.0"
versions = "0.53.0"
hilt = "1.3.0"
kotlinx-datetime = "0.7.1"
desugar = "2.1.5"
paging = "3.3.6"

[libraries]
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-common = { module = "org.jetbrains.androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigation-runtime = { module = "org.jetbrains.androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
compose-runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "androidx-compose" }
hilt-lifecycle-viewmodel-compose = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "hilt" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
multiplatform-locale = { module = "com.vanniktech:multiplatform-locale", version.ref = "multiplatform-locale" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
